# Generated by Django 4.1.1 on 2023-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line", "0015_selection_line_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="num",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
