# Generated by Django 4.2.2 on 2023-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0016_members_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='reserved',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
