# Generated by Django 4.2.2 on 2024-01-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0017_capacity_reserved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
