# Generated by Django 4.2.2 on 2024-01-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0018_delete_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='common',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
