# Generated by Django 4.2.2 on 2025-01-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0019_capacity_common'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('lines', models.CharField(max_length=255)),
                ('shared_line', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_month_one',
            new_name='cardiology',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_month_three',
            new_name='dermatology',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_month_two',
            new_name='elective_one',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_week_one',
            new_name='elective_three',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_week_three',
            new_name='elective_two',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='minor_week_two',
            new_name='emergency',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='ortopedix_one',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='ortopedix_two',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='pack_three',
            new_name='infectious',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='pack_one',
            new_name='orthopedix',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='pack_two',
            new_name='psychiatry',
        ),
        migrations.RemoveField(
            model_name='members',
            name='urology_one',
        ),
        migrations.RemoveField(
            model_name='members',
            name='urology_two',
        ),
    ]
