# Generated by Django 4.2.2 on 2025-01-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0020_shared_rename_minor_month_one_members_cardiology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared',
            old_name='lines',
            new_name='shared_unit',
        ),
        migrations.RemoveField(
            model_name='shared',
            name='shared_line',
        ),
    ]
