# Generated by Django 4.2.2 on 2025-03-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0021_rename_lines_shared_shared_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='dermatology',
        ),
        migrations.RemoveField(
            model_name='members',
            name='family',
        ),
        migrations.RemoveField(
            model_name='members',
            name='health',
        ),
        migrations.RemoveField(
            model_name='members',
            name='infectious',
        ),
        migrations.RemoveField(
            model_name='members',
            name='psychiatry',
        ),
    ]
