# Generated by Django 4.2.2 on 2025-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0022_remove_members_dermatology_remove_members_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='num',
            field=models.IntegerField(),
        ),
    ]
