# Generated by Django 4.2.2 on 2025-03-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0023_alter_members_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
