# Generated by Django 4.2.2 on 2025-03-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0024_members_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shared',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='capacity',
            table='line_capacity',
        ),
        migrations.AlterModelTable(
            name='members',
            table='line_members',
        ),
        migrations.AlterModelTable(
            name='selection',
            table='line_selection',
        ),
        migrations.AlterModelTable(
            name='shared',
            table='line_shared',
        ),
    ]
