# Generated by Django 4.2.2 on 2025-03-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0025_alter_capacity_id_alter_members_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='full',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='remain',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='reserved',
            field=models.IntegerField(),
        ),
    ]
