# Generated by Django 4.2.2 on 2025-03-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0026_alter_capacity_full_alter_capacity_remain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='members',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
