# Generated by Django 4.2.2 on 2025-03-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventconcurrentlogins', '0002_alter_visitor_id'),
        ('line', '0027_members_first_members_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('preventconcurrentlogins.visitor',),
        ),
    ]
