# Generated by Django 4.2.2 on 2025-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0028_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='common',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='cardiology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='elective_one',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='elective_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='elective_two',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='emergency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='first',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='gynocology',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='internal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='last',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='line',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='logged',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='orthopedix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='pediatrics',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='surgery',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
