# Generated by Django 4.2.2 on 2025-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0029_alter_capacity_common_alter_capacity_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='members',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
