# Generated by Django 4.2.2 on 2025-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0030_alter_members_first_alter_members_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(default='processing', max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
