# Generated by Django 4.2.2 on 2025-03-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0031_userimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimportjob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
