# Generated by Django 4.2.2 on 2025-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0032_alter_userimportjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='imports/capacity/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userimportjob',
            name='import_file',
            field=models.FileField(upload_to='imports/user/'),
        ),
    ]
