# Generated by Django 4.2.2 on 2025-03-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0033_capacityimportjob_alter_userimportjob_import_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapacityImportJob',
        ),
    ]
